// This constant holds the full text of the GINA 2025 guide.
// The AI assistant will use this as its sole source of knowledge.
export const GINA_DOCUMENT_TEXT = `
[The full text of the GINA 2025 document provided in the user's prompt would be inserted here. 
This is a very large string containing all 274 pages of OCR'd text.]

Global Strategy for Asthma Management and Prevention (2025 update)
The reader acknowledges that this report is intended as an evidence-based asthma management strategy, for the use of healthcare providers and policy-makers...
...
...
[...many pages of text...]
...
...
989. Brusselle GG, Koppelman GH. Biologic therapies for severe asthma. N Engl J Med 2022; 386: 157-171.
`;